### ISSUE TITLE
Enhancing OPDS - Open Publication Synchronization Service

### ISSUE THREAD

**Issue by Fmstrat** [Feedbooks/opds-test-catalog#1]
Hi everyone,

I'd like to make a proposal that may be of interest to you based on your backgrounds:

@janeczku - Author of Calibre-web
@HadrienGardeur - Maintainer of this repo and part of the OPDS community
@opds-community - The OPDS community
@geometer - Author or FBReader

Hopefully I've defined you all appropriately, but if not, my apologies. I'm sure there are others that make sense to pull into this conversion, and hopefully those already mentioned can reference them here.

While the OPDS spec is widely used (http://opds-spec.org/), one thing that has not yet been standardized in open readers is synchronization of read status, notes, bookmarks, and highlights. Many reader applications have this features (including FBReader), but while open, they are proprietary in-built systems.

My proposal is the creation of OPSS (Open Publication Synchronization Service) to accompany OPDS and hopefully be integrated into many of the solutions offering OPDS.

Initial considerations:
1. Web based, to ensure compatibility with existing OPDS solutions
2. JSON or XML response to allow for future addition of fields without breaking backwards compatibility
3. Back-end storage of data is up to the software developer, but guidance around DB structure or on-filesystem structures could be provided 
4. Guidance around authentication should be determined. (Shared user/pass with OPDS? API Key for public libraries? etc)
5. URL service location (always a subdirectory of OPDS to not require a separate URL?)
6. Should the spec allow for synchronization of items outside the OPDS library?

The following methods should be considered for implementation (naming is placeholder):
- **setposition**: Sets the current and furthest read position for 1 pub
- **getposition**: Gets the current and furthest read position 1 pub
- **getallpositions**: Gets all positions for multiple pubs (for quick synchronization of all books in the reader at load time for apps)
- **getmeta**: Gets both read positions, notes, bookmarks, and highlights 1 pub
- **setmeta**: Sets both read positions, notes, bookmarks, and highlights for 1 pub

Anyone interested in pursuing this?

**Comment by geometer** [comment]
Hi,

FBReader uses own (closed) API to sync positions/bookmarks with https://books.fbreader.org/. That would be great to switch to some commonly used protocol.

There are at least two technical questions to complete the idea:

(1) How to identify a book? Note that ePub is not the only book format.
(2) How to record a position?

**Comment by Fmstrat** [comment]
> (1) How to identify a book? Note that ePub is not the only book format.

Perhaps MD5 the file for a unique id?

> (2) How to record a position?

Count the words up the first word displayed on screen. That becomes the starting line for any reader, maybe? That also allows us to calculate percent read, and pages by defining average number of words per screen.

**Comment by Fmstrat** [comment]
Given the time frame since this conversation started, I wanted to check in on if there is any interest in building this out.

Adding the below to the chain because I believe they are likely candidates for initial implementations (along with calibre-web from a server side) of a cross-platform solution (common platforms, actively developed, and FOSS).

@axet - Author of Book Reader
@babluboy - Author of Bookwork

**Comment by HadrienGardeur** [comment]
I think this discussion is interesting but it's on the wrong repo. I'm going to try the new Github feature to move this to the right place.

**Comment by HadrienGardeur** [comment]
@Fmstrat 

Too bad, I can't transfer the issue to a different organization. Do you mind opening this issue in https://github.com/opds-community/drafts/issues where it belongs?

**Comment by Fmstrat** [comment]
And migrated. Thanks @HadrienGardeur!
